version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=datalouna
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
      - migrate  # Ensure migrations run before app starts
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start  # Start app after migrations

  migrate:
    build: .
    depends_on:
      db:
        condition: service_healthy  # Only run if PostgreSQL is healthy
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=datalouna
    volumes:
      - .:/app
      - /app/node_modules
    command: npx knex migrate:latest  # Run migrations

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: datalouna
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:  # Add healthcheck to ensure PostgreSQL is ready
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

volumes:
  db_data:
